# Change these first
owner: web-mighty-io # Your GitHub username
repo: status # Your GitHub repository name

# Add your sites here
sites:
  - name: Web Mighty
    url: https://web-mighty.io

status-website:
  # Add your custom domain below, or remove the next line if you don't have a domain
  cname: status.web-mighty.io
  # Uncomment the following line if you don't have a custom domain and add your repo name
  # baseUrl: /upptime
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Status
  introTitle: "Status of web-mighty.io"

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
